name: Deploy application to Droplet

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [main]
  # workflow_dispatch:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: setup git config
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"

      - name: Install Dependencies
        run: npm install --force

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build React Docker Image
        run: docker build --tag test-app -f Dockerfile .

      - name: Tag image
        run:  docker tag test-app ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest

      - name: Copy docker-compose.yml to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: docker-compose.yml
          target: /root

      - name: SSH to Droplet and Update Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            docker compose down || true
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} docker compose up -d
